.github/workflows/ci.yml
.github/workflows/ecosystem-ci-trigger.yml

chore: 🤖 disable ci

---

packages/vite/package.json
pnpm-lock.yaml

chore: 🤖 use specific nightly

---

packages/vite/src/node/plugins/asset.ts
packages/vite/src/node/plugins/css.ts

fix: remove unused directive

---

packages/vite/src/node/build.ts

1. rolldown has been builtin supported dataurl

conditional swtich dataurl plugin

---

packages/vite/src/node/build.ts
packages/vite/src/node/plugins/index.ts

perf: reduce enable a plugin in production mode

---

packages/vite/src/node/plugins/css.ts

css plugin filterable

---

packages/vite/src/node/plugins/html.ts

hook using `object` with `filter` field instead of function, nothing change else

feat:  html filterable

---

packages/vite/package.json
pnpm-lock.yaml

chore:  bump rolldown

---

packages/vite/src/node/build.ts
packages/vite/src/node/plugins/index.ts

perf:  use default resolver

---

packages/vite/rollup.dts.config.ts
packages/vite/src/node/index.ts

feat: export transformWithOxc

---

packages/vite/src/node/__tests__/build.spec.ts
packages/vite/src/node/build.ts
packages/vite/src/node/packages.ts
packages/vite/src/node/plugins/esbuild.ts
vitest.config.e2e.ts

feat: enable lib mode tests

---

packages/vite/src/node/__tests__/plugins/define.spec.ts
packages/vite/src/node/plugins/define.ts
playground/define/__tests__/define.spec.ts
playground/js-sourcemap/__tests__/js-sourcemap.spec.ts

feat: use oxc for non-native define plugin

---

packages/vite/package.json
packages/vite/src/node/build.ts
packages/vite/src/node/plugins/css.ts
playground/minify/vite.config.js
pnpm-lock.yaml

feat: use lightningcss by default for cssMinify

---

packages/vite/src/node/__tests__/plugins/oxc.spec.ts
packages/vite/src/node/plugins/oxc.ts

Correctly inject helpers to IIFE workers.

fix: accept worker iife format

---

packages/vite/package.json
packages/vite/src/node/constants.ts
pnpm-lock.yaml

- feat: update rolldown
- fix: make this.environment available in outputOptions hook

feat: update rolldown

---

packages/vite/src/node/plugins/oxc.ts

https://github.com/vitejs/rolldown-vite/pull/63 added `jsx` filters to the internal oxc plugin. But this was actually slightly different from what react plugin needed. The react plugin configures which file react-refresh transform is applied, not which file jsx transform is applied.
This PR changes the option to `jsxRefresh` filter.

feat(oxc)!: jsxRefresh filter

---

packages/vite/package.json
pnpm-lock.yaml

chore: bump rolldown

---

packages/vite/src/node/publicUtils.ts

Export `rolldownVersion`. I forgot to expose this.

fix: export `rolldownVersion`

---

packages/vite/src/node/optimizer/pluginConverter.ts

resolve correctly when the importer has a namespace.
fixes #108

feat(optimizer): improve esbuild plugin conversion compat

---

packages/vite/src/node/config.ts

Make the message more correct.

fix: update oxc esbuild option warning message

---

packages/vite/src/node/config.ts

chore: oxc esbuild option warning message grammar

---

packages/vite/src/node/publicUtils.ts
packages/vite/src/node/utils.ts

reexport `withFilter`
cc @TheAlexLichter

feat: reexport `withFilter` from rolldown

---

packages/vite/src/node/config.ts
packages/vite/src/node/plugins/asset.ts

perf: add filter to asset plugin

---

packages/vite/src/node/config.ts
packages/vite/src/node/plugins/oxc.ts

`Omit<>` should be used instead of `Exclude<>`

fix(oxc): correctly type oxc options

---

packages/vite/src/node/build.ts
packages/vite/src/node/plugins/reporter.ts

feat(native-plugin): use native reporter plugin

---

packages/vite/src/node/plugins/asset.ts

fix(asset): regex filter should not force query to be included

---

packages/vite/src/node/plugins/oxc.ts

refs https://github.com/oxc-project/oxc/pull/10491#issuecomment-2823195571

fix: set `typescript.removeClassFieldsWithoutInitializer` for `useDefineForClassFields=false`

---

packages/vite/src/node/plugin.ts
packages/vite/src/node/plugins/worker.ts
packages/vite/src/node/plugins/workerImportMetaUrl.ts

feat(types): add `shouldTransformCachedModule` for compat

---

packages/vite/types/internal/rollupTypeCompat.d.ts

feat(types): add `Rollup.RollupWatcherEvent` type

---

packages/vite/src/node/config.ts

fix(config): make dynamic import work in config

---

packages/vite/src/node/build.ts
playground/vitestSetup.ts

fix: watch related fixes

---

packages/vite/src/node/optimizer/index.ts

Suppress warnings for optimizer by default to align with normal Vite.
fixes https://github.com/vitejs/rolldown-vite/issues/153

fix(optimizer): suppress warnings for optimizer

---

playground/assets/vite.config-encoded-base.js
playground/assets/vite.config-relative-base.js
playground/assets/vite.config-runtime-base.js
playground/assets/vite.config-url-base.js
playground/optimize-deps/__tests__/optimize-deps.spec.ts
vitest.config.e2e.ts

test: reduce diff with normal Vite

---

packages/vite/LICENSE.md
packages/vite/package.json
packages/vite/src/node/optimizer/rolldownDepPlugin.ts
packages/vite/src/node/plugins/asset.ts
packages/vite/src/node/plugins/assetImportMetaUrl.ts
packages/vite/src/node/plugins/dynamicImportVars.ts
packages/vite/src/node/plugins/importAnalysisBuild.ts
packages/vite/src/node/plugins/modulePreloadPolyfill.ts
packages/vite/src/node/plugins/oxc.ts
packages/vite/src/node/plugins/resolve.ts
packages/vite/src/node/plugins/wasm.ts
packages/vite/src/node/utils.ts
pnpm-lock.yaml

refactor: use util functions from `@rolldown/pluginutils`

---

packages/vite/src/node/optimizer/index.ts

fix(optimizer): pass define option to optimizer

---

packages/vite/src/node/plugins/esbuild.ts

chore: add deprecation warning for `transformWithEsbuild`

---

packages/vite/src/node/build.ts

Hi sapphi, thank you for helping me adapt the `reporterPlugin`. I originally planned to align with it, but I ended up forgetting.
This is a small alignment.

fix(native-plugin): align native reporter plugin with non-native one

---

packages/vite/src/node/__tests_dts__/plugin.ts
packages/vite/src/node/plugin.ts

refs https://github.com/rolldown/rolldown/pull/4568
close https://github.com/vitejs/rolldown-vite/issues/117

feat(types): allow rollup plugin to be assigned to `plugins` option

---

packages/vite/rollup.config.ts
packages/vite/rollup.dts.config.ts

close https://github.com/vitejs/rolldown-vite/issues/175
close https://github.com/vitejs/rolldown-vite/issues/177

fix: use correct self-reference import

---

packages/vite/src/node/plugins/define.ts

Align with the original define plugin logic.

feat(native-plugin): support `import.meta.env.*` for native define plugin

---

packages/vite/src/node/config.ts

chore: tweak `optimizeDeps.esbuildOptions` deprecate message

---

packages/vite/src/node/build.ts
packages/vite/src/node/plugins/worker.ts
playground/multiple-entrypoints/vite.config.js

feat: enable preserveEntrySignatures

---

packages/vite/src/node/build.ts

These properties should be enumerable so that it's more similar to normal properties.

fix: make `viteMetadata` and `modules` enumerable

---

packages/vite/src/node/plugins/importAnalysisBuild.ts

perf: set filter for import analysis build plugin

---

packages/vite/src/node/plugins/css.ts

fix(css): set moduleType in css-post plugin

---

packages/vite/src/node/plugins/wasm.ts

Wait for https://github.com/rolldown/rolldown/pull/5120

feat(native-plugin): pass `decodedBase` to `nativeWasmHelperPlugin`

---

packages/vite/src/node/__tests__/plugins/oxc.spec.ts
packages/vite/src/node/plugins/oxc.ts

fix: accept umd with only default export

---

packages/vite/package.json
packages/vite/src/node/plugins/dynamicImportVars.ts
playground/package.json
pnpm-lock.yaml

feat: update rolldown and support custom configs for native dynamic import vars plugin

---

packages/vite/src/node/build.ts

feat: enable `treeshake.commonjs` by default

---

packages/vite/src/node/__tests__/plugins/fixtures/oxc-tsconfigs/decorator-metadata/tsconfig.json
packages/vite/src/node/__tests__/plugins/oxc.spec.ts
packages/vite/src/node/plugins/esbuild.ts
packages/vite/src/node/plugins/oxc.ts

refs https://github.com/vitejs/rolldown-vite/issues/309

feat: enable decorator-metadata transform automatically

---

packages/vite/src/node/build.ts
playground/lib/__tests__/lib.spec.ts

To align with original Vite's behavior.

fix(lib): keep annotation comments for es output

---

packages/vite/src/node/build.ts
packages/vite/src/node/plugins/worker.ts

fix: reset viteMetadata in watch mode

---

packages/vite/package.json
packages/vite/src/node/__tests__/plugins/define.spec.ts
packages/vite/src/node/__tests__/plugins/oxc.spec.ts
packages/vite/src/node/server/pluginContainer.ts
playground/lib/__tests__/lib.spec.ts
playground/package.json
pnpm-lock.yaml

> #### 💥 BREAKING CHANGES
> - **rolldown**: remove unfinished module federation support (https://github.com/rolldown/rolldown/pull/5471) by @Boshen
> - disable strictExecutionOrder by default (https://github.com/rolldown/rolldown/pull/5436) by @hyf0
https://github.com/rolldown/rolldown/releases/tag/v1.0.0-beta.30

feat: bump rolldown

---

packages/vite/src/node/config.ts

fix: watch the config file itself

---

packages/vite/src/node/plugins/manifest.ts

fix(native-plugin): generate a more readable manifest

---

packages/vite/package.json
pnpm-lock.yaml

see https://github.com/rolldown/rolldown/pull/6118

chore: bump `rolldown-plugin-dts`

---

packages/vite/src/node/server/environments/fullBundleEnvironment.ts
packages/vite/src/node/server/hmr.ts
packages/vite/src/node/server/index.ts
packages/vite/src/node/server/middlewares/indexHtml.ts
playground/hmr-full-bundle-mode/__tests__/hmr-full-bundle-mode.spec.ts

wip: use dev api

---

packages/vite/src/node/plugins/oxc.ts

https://babeljs.io/docs/babel-preset-typescript#jsxpragma

fix(oxc): set typescript jsx options
