packages/vite/rollup.dts.config.ts
Reopening https://github.com/rolldown/vite/pull/28 to just workaround this part `replaceConfusingTypeNames`. This should hopefully make package build pass, so CI can check `test-serve`.
=> chore: silence vite package dts build error

packages/vite/rollup.dts.config.ts, packages/vite/src/node/optimizer/index.ts
Currently `optimizeDeps.exclude` is externalized at the config level `rolldown.rolldown({ external: ... })` and it looks like `rolldownCjsExternalPlugin` doesn't have a chance to fixup cjs external. This manifests as test failures in `playground/external`.
Since `rolldownCjsExternalPlugin` also handles non-cjs external, I simply removed rolldown's `external` config and it looks like tests are passing.
Only the last commit https://github.com/rolldown/vite/pull/31/commits/5edc81d9aaab04b226adc2fbbdf5b017b01ef7cd is the actual fix and first commits are the same one from https://github.com/rolldown/vite/pull/28.
=> fix: externalize `optimizeDeps.exclude` via `rolldownCjsExternalPlugin` (fix `test-serve playground/external`)

packages/vite/src/node/plugins/assetImportMetaUrl.ts
filterable asset import meta url
1. I change `transform` hook from function to object with `filter`, change nothing else.
=> filterable asset import meta url

packages/vite/src/node/plugins/worker.ts
=> worker filterable

packages/vite/src/node/build.ts
1. rolldown `warnLog` only has `code` and `message` two field, so disable other log filter that use unsupported 
field, here is an example : 
```bash
warnLog:  {
code: 'UNRESOLVED_IMPORT',
message: '\x1B[33m[UNRESOLVED_IMPORT] Warning:\x1B[0m "./src/main.jsx" is imported by "index.html", but could not be resolved – treating it as an external dependency.\n'
}
Error: [vite]: Rollup failed to resolve import "undefined" from "undefined".
```
=> fix: disable vite log filter

.github/workflows/publish-commit.yml, package.json, packages/plugin-legacy/package.json, packages/vite/package.json, playground/config/__tests__/config.spec.ts, playground/external/package.json, playground/legacy/package.json, pnpm-lock.yaml
In order to publish the package the name in `packages/vite/package.json` is changed to `rolldown-vite`.
We'll need to remember to revert this when we eventually move this work over to the main `vitejs/vite` repo.
=> chore: enable continuous release under rolldown-vite

packages/vite/src/node/plugins/oxc.ts
Conside the react plugin has two edge case
- ssr need to disable refresh transformer, here disabled `refresh` at internal
- the js mdx extension should be enabled refresh transformer, here add a `jsxInclude` option to do it.
=> feat: add oxc jsxInclude and jsxExclude

packages/vite/src/node/idResolver.ts, packages/vite/src/node/plugins/css.ts, packages/vite/src/node/plugins/index.ts, packages/vite/src/node/plugins/resolve.ts, packages/vite/src/node/server/environment.ts, packages/vite/src/node/server/pluginContainer.ts
requires https://github.com/rolldown/rolldown/pull/2869
=> feat: use native plugin for create id resolver

docs/_data/blog.data.ts, packages/vite/src/node/config.ts
=> feat: use rolldown for config loader

packages/vite/src/node/__tests__/plugins/css.spec.ts, packages/vite/src/node/build.ts, packages/vite/src/node/plugins/css.ts, packages/vite/src/node/plugins/worker.ts, playground/css-codesplit/__tests__/css-codesplit.spec.ts, playground/js-sourcemap/__tests__/js-sourcemap.spec.ts, playground/worker/__tests__/es/worker-es.spec.ts, playground/worker/__tests__/relative-base/worker-relative-base.spec.ts
~~need to check why the tests are failing~~ done
=> feat: use rolldown minify

packages/vite/src/node/optimizer/index.ts, packages/vite/src/node/optimizer/scan.ts
=> perf: do less on js side for optimizer

packages/vite/src/node/__tests__/plugins/modulePreloadPolyfill/modulePreloadPolyfill.spec.ts, packages/vite/src/node/build.ts, packages/vite/src/node/plugins/oxc.ts, playground/lib/__tests__/lib.spec.ts
~~TODO: Check if it's working again later~~ done
=> feat: use oxc for lowering

eslint.config.js, packages/vite/package.json, packages/vite/rollup.dts.config.ts, packages/vite/src/node/build.ts, packages/vite/src/node/index.ts, packages/vite/src/node/optimizer/index.ts, packages/vite/src/node/optimizer/scan.ts, packages/vite/src/node/plugins/css.ts, packages/vite/src/node/plugins/esbuild.ts, packages/vite/src/node/plugins/oxc.ts, packages/vite/src/node/publicUtils.ts, packages/vite/types/internal/esbuildOptions.d.ts, pnpm-lock.yaml
=> feat: make esbuild optional peer dep

packages/vite/src/node/plugins/css.ts
I meet the error when enable the lib test at vite-plugin-vue. ref https://github.com/rolldown/vite-plugin-vue/actions/runs/12293389227/job/34305975962?pr=1
```
[plugin vite:esbuild-transpile] index.js.umd.cjs:1:16
Error: Transform failed with 1 error:
index.js.umd.cjs:1:16: ERROR: Expected ")" but found "__vite_style__"
Expected ")" but found "__vite_style__"
1  |  (function(glvar __vite_style__ = document.createElement('style');__vite_style__.textContent = ".card{padding:4rem}\n/*$vite$:1*/";document.head.appendChild(__vite_style__);obal, factory) {
|                  ^
2  |    typeof exports === 'object' && typeof module !== 'undefined' ?  factory(exports) :
3  |    typeof define === 'function' && define.amd ? define([exports], factory) :
```
I debugger it and found the rolldown output …
=> fix(css): inline css insert for single quote `use strict`

packages/vite/src/node/build.ts, packages/vite/types/metadata.d.ts
I added a quick and dirty workaround for `chunk.modules` mutation. I tested on unocss and this seems to fix some tests ~(but not all :cry:).~ (EDIT: it turned out other test failure is due to oxc transform https://github.com/oxc-project/oxc/issues/9192 and technically unocss side is broken https://github.com/unocss/unocss/issues/4436).
Probably this isn't good for the long run (considering rolldown level css support?), but if this trick can save ecosystem for the time being, it might be worth it.
=> fix: allow chunk.modules mutation on js side

packages/vite/src/node/optimizer/index.ts
There is duplicate `createRequire` in `playground/ssr-deps/node_modules/.vite/deps_ssr/chunk-B6b7aAQJ.js` due to Rolldown's automatic polyfill and Vite's banner.
```js
import { createRequire } from 'module';const require = createRequire(import.meta.url);
import { createRequire } from "module";
//#region rolldown:runtime
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function() {
return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __require = /* @__PURE__ */ createRequire(import.meta.url);
//#endregion
export { __commonJS, __require };
```
Current Vite SSR is tolerating this code https://github.com/vitejs/vite/issues/19617, but this gets surfaced when oxc transform rejected this code …
=> fix: remove duplicate `createRequire` in optimizer

packages/vite/src/node/plugins/oxc.ts
Merge jsx options in tsconfig even if `oxc: { development: true }` is set (this is the default).
=> fix(transform): merge tsconfig jsx options with oxc jsx options correctly

packages/vite/src/node/config.ts
When the top-level `resolve.preserveSymlinks` is set, derive it to `optimizeDeps.rollupOptions.resolve.symlinks`.
This fixes the ecosystem-ci with storybook.
=> fix(optimizer): derive `resolve.symlinks` option properly

packages/vite/src/node/plugins/modulePreloadPolyfill.ts, packages/vite/src/node/plugins/wasm.ts, packages/vite/src/node/utils.ts
Related https://github.com/rolldown/rolldown/issues/3964, https://github.com/rolldown/rolldown/issues/3970
~Probably we shouldn't need to do this, but I'm not sure a way forward, so I think we can use exact regex for the time being.~  see discussion in https://github.com/rolldown/rolldown/pull/3972
Also I wanted to see if this is enough to make build pass on stackblitz and it looks like working now https://stackblitz.com/edit/vitejs-vite-8n2i1q5j?file=package.json&terminal=build
=> fix: use exact regexp filter for virtual module

packages/vite/src/node/plugins/worker.ts
Suppress export related warnings in worker build as these will be output because `preserveEntrySignatures` is not supported by rolldown.
=> fix(worker): suppress export related warnings in worker build

packages/vite/src/node/build.ts
If this is done by an assignment, it gets detected on the rolldown side and rolldown tries to sync.
https://github.com/rolldown/rolldown/blob/f4c5ff27799f2b0152c689c398e61bc7d30429ff/packages/rolldown/src/utils/transform-to-rollup-output.ts#L87
This is not needed and has a big overhead especially when sourcemaps are enabled.
To avoid that from happening, I replaced the assignment with `Object.defineProperty` (this does not trigger the setter).
=> perf: define viteMetadata instead of assign

packages/vite/src/node/baseEnvironment.ts, packages/vite/src/node/config.ts, packages/vite/src/node/optimizer/index.ts, packages/vite/src/node/plugins/index.ts
config hash should now include rollupOptions instead of esbuildOptions.
=> fix(optimizer): include rollupOptions in config hash

packages/vite/src/node/plugins/resolve.ts
`plugin.apply` is not respected for internal plugins so we cannot used it.
=> fix(native-plugin): disable optimizerResolvePlugin correctly

packages/vite/src/node/build.ts, packages/vite/src/node/cli.ts
Make sure people are aware that `rolldown-vite` is running by changing the console output from "vite" to "rolldown-vite"
We can also do "Vite (with Rolldown)" but I felt it is a bit too lengthy.
=> chore: add rolldown-vite indicator

eslint.config.js, packages/vite/src/node/index.ts, packages/vite/types/internal/rollupTypeCompat.d.ts
Add some `Rollup*` types to `Rollup` type exposed from Vite so that the migration is easier.
=> feat(types): make exposed `Rollup` type more compatible with Rollup

packages/vite/src/node/build.ts, packages/vite/src/node/watch.ts, playground/assets/__tests__/assets.spec.ts, playground/assets/vite.config.js, playground/package.json, playground/vitestSetup.ts, pnpm-lock.yaml
needs ~~https://github.com/rolldown/rolldown/issues/2830,~~ ~~https://github.com/rolldown/rolldown/issues/2831~~
~~also should add `build.watch.notify`~~
=> feat: use Rolldown's watch API

packages/vite/src/node/plugins/css.ts, packages/vite/src/node/plugins/oxc.ts
This change is now needed because rolldown does not inject `"use strict"` sometimes. (rollup always injects it)
https://github.com/vitejs/vite-plugin-vue/blob/6737f06884db49cbeb59da8b63a3dae9d209b789/playground/vue-lib/__tests__/vue-lib.spec.ts#L26-L35 covers this behavior.
=> fix(css): inject CSS correctly when `cssCodesplit: true` and IIFE/UMD

packages/vite/src/node/__tests__/plugins/json.spec.ts, packages/vite/src/node/build.ts, packages/vite/src/node/plugins/dynamicImportVars.ts, packages/vite/src/node/plugins/importMetaGlob.ts, packages/vite/src/node/plugins/index.ts, packages/vite/src/node/plugins/json.ts, packages/vite/src/node/plugins/manifest.ts, packages/vite/src/node/plugins/modulePreloadPolyfill.ts, packages/vite/src/node/plugins/oxc.ts, packages/vite/src/node/plugins/reporter.ts, packages/vite/src/node/plugins/wasm.ts, packages/vite/src/node/plugins/worker.ts
Would you make a PR that does this refactor (moving the condition to the plugin file side) for all the native plugins first so that we can split the refactor and the behavior change?
_Originally posted by @sapphi-red in https://github.com/vitejs/rolldown-vite/pull/238#discussion_r2134943882_
=> refactor: move the condition related to `enableNativePlugin` to the plugin file side

packages/vite/src/node/__tests__/plugins/oxc.spec.ts, packages/vite/src/node/plugins/oxc.ts
Correctly inject helpers to UMD format without exports.
refs #94
=> fix: accept umd without exports

packages/vite/src/node/plugins/oxc.ts
The native plugin uses the internal rolldown context to resolve tsconfig, so we use js plugin in dev environment.
=> feat(native-plugin): use js oxc transform plugin in dev environment

packages/vite/src/node/plugins/dynamicImportVars.ts
The native plugin uses the `transform_ast` hook, so we use the js plugin in the dev environment.
=> feat(native-plugin): use js dynamic import vars plugin in dev environment

packages/vite/src/node/plugins/index.ts
The native plugin uses the internal rolldown context, so we use js plugin in dev environment.
=> feat(native-plugin): use js alias plugin in dev environment

packages/vite/src/node/plugins/wasm.ts
The native plugin uses the internal rolldown context, so we use js plugin in dev environment.
=> feat(native-plugin): use js wasm helper in dev environment

packages/vite/src/node/plugins/worker.ts
The native plugin uses the `transform_ast` hook, so we use the js plugin in the dev environment.
=> feat(native-plugin): use js web worker post in dev environment

packages/vite/src/node/plugins/modulePreloadPolyfill.ts
- ~~Vite only used this plugin for build, so removing this plugin won't affect dev~~
- ~~The native plugin is fully aligned in build environment~~
~~What I'm curious about is whether we can move it into `resolveBuildPlugins`.~~
The native plugin used internal context, so we use js plugin in dev environment.
=> feat(native-plugin): use js modulepreload polyfill plugin in dev environment

packages/vite/src/node/plugins/resolve.ts
`finalizeBareSpecifier` / `finalizeOtherSpecifiers` was not called because whether the deps optimizer is enabled was not detected correctly.
=> fix(native-plugin): run optimizer correctly

packages/vite/src/node/plugins/resolve.ts, playground/optimize-deps/__tests__/optimize-deps.spec.ts, pnpm-lock.yaml
See https://github.com/vitejs/vite/pull/20029
The native plugins test fails are expected as this PR only changes the JS plugins.
fixes #165
=> fix: importing an optional peer dep should throw an runtime error

packages/vite/src/node/build.ts
`viteMetadata` was not able to access from the `bundle` parameter of `writeBundle` hook.
fixes #264
=> fix: set viteMetadata for `writeBundle` hook

packages/vite/rolldown.config.ts, packages/vite/src/node/plugins/oxc.ts
`import.meta.url` was replaced in build and was pointing a different directory.
Includes https://github.com/vitejs/vite/pull/20235
=> fix: resolve oxc runtime from Vite directory correctly

packages/vite/package.json, packages/vite/src/node/plugins/resolve.ts, playground/package.json, pnpm-lock.yaml
Wait for https://github.com/rolldown/rolldown/pull/5093
=> feat: update rolldown and support `resolveSubpathImports` for `oxcResolvePlugin`

packages/vite/src/node/plugins/oxc.ts
- Closes https://github.com/vitejs/vite-plugin-react/issues/514
`@vitejs/plugin-react` has this check `isJSX || code.includes(jsxImportRuntime) || code.includes(jsxImportDevRuntime)` for fast refresh. Since the default `filter` allows non-jsx file, this additional check is necessary on oxc refresh transform side.
I added a test case in https://github.com/vitejs/vite-plugin-react/pull/547 and confirmed it's fixed by pkg.pr.new
=> fix: disable refresh for non-jsx without react import

packages/vite/src/node/__tests__/config.spec.ts, packages/vite/src/node/build.ts, packages/vite/src/node/config.ts, packages/vite/src/node/optimizer/index.ts, packages/vite/src/node/utils.ts
Introduced `build.rolldownOptions`, `worker.rolldownOptions`, `optimizeDeps.rolldownOptions`, `ssr.optimizeDeps.rolldownOptions`.
Each `rolldownOptions` are synced with `rollupOptions` (modifying one will update the other).
It is not runtime deprecated yet.
Also the internal code still prefer to use `rollupOptions` to keep the diff smaller.
=> refactor: introduce `*.rolldownOptions` and deprecate `*.rollupOptions`

packages/vite/src/node/__tests__/config.spec.ts, packages/vite/src/node/build.ts
After https://github.com/vitejs/rolldown-vite/pull/348, cloudflare plugin's `platform: "neutral"` is overwritten with `platform: "node"` and broke rsc plugin examples.
=> fix: respect `rollupOptions.platform` options

packages/vite/src/node/__tests__/plugins/define.spec.ts, packages/vite/src/node/build.ts, packages/vite/src/node/config.ts, packages/vite/src/node/plugins/define.ts, packages/vite/src/node/plugins/dynamicImportVars.ts, packages/vite/src/node/plugins/importAnalysisBuild.ts, packages/vite/src/node/plugins/importMetaGlob.ts, packages/vite/src/node/plugins/index.ts, packages/vite/src/node/plugins/manifest.ts, packages/vite/src/node/plugins/modulePreloadPolyfill.ts, packages/vite/src/node/plugins/oxc.ts, packages/vite/src/node/plugins/reporter.ts, packages/vite/src/node/plugins/wasm.ts, packages/vite/src/node/plugins/worker.ts, playground/glob-import/__tests__/glob-import.spec.ts, playground/js-sourcemap/__tests__/js-sourcemap.spec.ts, playground/minify/vite.config.js
This PR enables the current stable native plugins. The default value of `experimental.enableNativePlugin` is changed from `'resolver'` to `'v1'`.
=> feat: enable all native plugins by default

packages/vite/src/node/build.ts
This will add additional overhead when the native plugin is disabled because the transformer will try to run even if it's already done by the js plugin, but that should be fine.
refs https://github.com/vitejs/rolldown-vite/issues/440, https://github.com/vitejs/rolldown-vite/issues/404
=> fix: set transform target
